spring:
  application:
    name: sqlvsnosql
  datasource:
    url: jdbc:mysql://localhost:3306/employees_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&sessionVariables=sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    username: "vlado"
    password: "vlado"
    hikari:
      connection-test-query: "SELECT 1"
      minimum-idle: 2
      maximum-pool-size: 100
  liquibase:
    change-log: "classpath:/liquibase/db-init.yaml"
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate

server:
  port: 8082
